# Generated by Django 4.2.2 on 2023-11-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
