# Generated by Django 4.2.6 on 2023-11-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_course_thumbnail_alter_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='length',
            field=models.DurationField(default=0),
        ),
    ]
