# Generated by Django 4.2.6 on 2023-11-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_speakers_webinar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='courses',
        ),
        migrations.AddField(
            model_name='cart',
            name='course',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
            preserve_default=False,
        ),
    ]
