# Generated by Django 4.2.6 on 2023-11-24 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_lesson_thumbnail_alter_lesson_video_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_thumbnail',
            field=models.FileField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='trailer',
            field=models.FileField(upload_to='media/videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='length',
            field=models.DurationField(default=datetime.timedelta(seconds=10)),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='thumbnail',
            field=models.FileField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='trailer',
            field=models.FileField(upload_to='media/videos/'),
        ),
    ]
