# Generated by Django 4.2.6 on 2023-11-24 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_course_course_thumbnail_alter_course_trailer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='length',
            field=models.DurationField(default=datetime.timedelta(seconds=102)),
        ),
    ]
