# Generated by Django 4.2.6 on 2023-11-25 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_lesson_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='length',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
